import type {
  FeatureDefinition,
  RuleRegistry,
  RuleSource,
  SpellDefinition,
  SpellGrant,
} from './models';
export const phb2024: RuleSource = {
  ruleset: '5e-2024',
  sourceId: 'phb-2024-private',
  sourceType: 'private-reference',
  verified: true,
};
const feature = (
  id: string,
  name: string,
  ownerType: FeatureDefinition['ownerType'],
  ownerId: string,
  level: number,
  summary: string,
  effects: FeatureDefinition['effects'] = [],
): FeatureDefinition => ({
  id,
  name,
  ownerType,
  ownerId,
  level,
  summary,
  effects,
  source: phb2024,
});
const featureList: FeatureDefinition[] = [
  feature(
    'druid-druidic',
    'Druidic',
    'class',
    'druid',
    1,
    'You know the secret Druidic language.',
  ),
  feature(
    'druid-primal-order',
    'Primal Order',
    'class',
    'druid',
    1,
    'Choose a magical or martial Druid role.',
  ),
  feature(
    'druid-spellcasting',
    'Spellcasting',
    'class',
    'druid',
    1,
    'Prepare and cast Druid spells using Wisdom.',
  ),
  feature(
    'druid-wild-shape',
    'Wild Shape',
    'class',
    'druid',
    2,
    'Spend a use to assume an eligible Beast form.',
    [{ type: 'grant-resource', resourceId: 'wild-shape' }],
  ),
  feature(
    'druid-wild-companion',
    'Wild Companion',
    'class',
    'druid',
    2,
    'Spend Wild Shape to summon a temporary familiar.',
  ),
  feature(
    'druid-subclass',
    'Druid Subclass',
    'class',
    'druid',
    3,
    'Gain a Druid subclass.',
    [{ type: 'unlock-subclass', level: 3 }],
  ),
  feature(
    'druid-ability-score-improvement-4',
    'Ability Score Improvement',
    'class',
    'druid',
    4,
    'Gain an eligible feat or improve ability scores.',
  ),
  feature(
    'druid-wild-resurgence',
    'Wild Resurgence',
    'class',
    'druid',
    5,
    'Exchange spell energy and Wild Shape uses.',
  ),
  feature(
    'druid-elemental-fury',
    'Elemental Fury',
    'class',
    'druid',
    7,
    'Choose improved cantrip or weapon damage.',
  ),
  feature(
    'druid-ability-score-improvement-8',
    'Ability Score Improvement',
    'class',
    'druid',
    8,
    'Gain an eligible feat or improve ability scores.',
  ),
  feature(
    'land-circle-spells',
    'Circle Spells',
    'subclass',
    'circle-of-the-land',
    3,
    'Your current land grants always-prepared spells.',
  ),
  feature(
    'land-natures-aid',
    'Land’s Aid',
    'subclass',
    'circle-of-the-land',
    3,
    'Channel Wild Shape into restorative natural magic.',
  ),
  feature(
    'land-natural-recovery',
    'Natural Recovery',
    'subclass',
    'circle-of-the-land',
    6,
    'Recover spell slots during a Short Rest once per Long Rest.',
  ),
  feature(
    'tiefling-darkvision',
    'Darkvision',
    'species',
    'tiefling',
    1,
    'See in darkness out to 60 feet.',
  ),
  feature(
    'tiefling-otherworldly-presence',
    'Otherworldly Presence',
    'species',
    'tiefling',
    1,
    'You know Thaumaturgy.',
  ),
  feature(
    'chthonic-legacy',
    'Chthonic Legacy',
    'species',
    'chthonic',
    1,
    'Gain necrotic resistance and legacy magic.',
    [{ type: 'grant-resistance', damageType: 'necrotic' }],
  ),
  feature(
    'farmer-skills',
    'Farmer Training',
    'background',
    'farmer',
    1,
    'Gain Animal Handling, Nature, and Carpenter’s Tools training.',
    [
      { type: 'grant-skill-proficiency', skill: 'animalHandling' },
      { type: 'grant-skill-proficiency', skill: 'nature' },
    ],
  ),
  feature(
    'tough-durability',
    'Tough',
    'feat',
    'tough',
    1,
    'Increase maximum Hit Points by 2 per character level.',
    [{ type: 'modify-hit-points-per-level', amount: 2 }],
  ),
];
const progression = [
  [
    1,
    2,
    4,
    { 1: 2 },
    0,
    ['druid-druidic', 'druid-primal-order', 'druid-spellcasting'],
  ],
  [2, 2, 5, { 1: 3 }, 2, ['druid-wild-shape', 'druid-wild-companion']],
  [3, 2, 6, { 1: 4, 2: 2 }, 2, ['druid-subclass']],
  [4, 3, 7, { 1: 4, 2: 3 }, 2, ['druid-ability-score-improvement-4']],
  [5, 3, 9, { 1: 4, 2: 3, 3: 2 }, 2, ['druid-wild-resurgence']],
  [6, 3, 10, { 1: 4, 2: 3, 3: 3 }, 3, []],
  [7, 3, 11, { 1: 4, 2: 3, 3: 3, 4: 1 }, 3, ['druid-elemental-fury']],
  [
    8,
    3,
    12,
    { 1: 4, 2: 3, 3: 3, 4: 2 },
    3,
    ['druid-ability-score-improvement-8'],
  ],
  [9, 3, 14, { 1: 4, 2: 3, 3: 3, 4: 3, 5: 1 }, 3, []],
] as const;
const spellRows: Array<
  [
    string,
    string,
    SpellDefinition['level'],
    SpellDefinition['school'],
    boolean,
    boolean,
    string[],
  ]
> = [
  ['druidcraft', 'Druidcraft', 0, 'transmutation', false, false, ['druid']],
  ['guidance', 'Guidance', 0, 'divination', false, true, ['druid']],
  ['produce-flame', 'Produce Flame', 0, 'conjuration', false, false, ['druid']],
  ['thorn-whip', 'Thorn Whip', 0, 'transmutation', false, false, ['druid']],
  ['fire-bolt', 'Fire Bolt', 0, 'evocation', false, false, []],
  ['ray-of-frost', 'Ray of Frost', 0, 'evocation', false, false, []],
  ['shocking-grasp', 'Shocking Grasp', 0, 'evocation', false, false, []],
  ['acid-splash', 'Acid Splash', 0, 'evocation', false, false, []],
  ['chill-touch', 'Chill Touch', 0, 'necromancy', false, false, []],
  ['thaumaturgy', 'Thaumaturgy', 0, 'transmutation', false, false, []],
  [
    'animal-friendship',
    'Animal Friendship',
    1,
    'enchantment',
    false,
    false,
    ['druid'],
  ],
  ['cure-wounds', 'Cure Wounds', 1, 'abjuration', false, false, ['druid']],
  ['entangle', 'Entangle', 1, 'conjuration', false, true, ['druid']],
  ['faerie-fire', 'Faerie Fire', 1, 'evocation', false, true, ['druid']],
  ['goodberry', 'Goodberry', 1, 'conjuration', false, false, ['druid']],
  ['healing-word', 'Healing Word', 1, 'abjuration', false, false, ['druid']],
  [
    'speak-with-animals',
    'Speak with Animals',
    1,
    'divination',
    true,
    false,
    ['druid'],
  ],
  ['burning-hands', 'Burning Hands', 1, 'evocation', false, false, []],
  ['blur', 'Blur', 2, 'illusion', false, true, []],
  ['fog-cloud', 'Fog Cloud', 1, 'conjuration', false, true, ['druid']],
  ['hold-person', 'Hold Person', 2, 'enchantment', false, true, []],
  ['sleep', 'Sleep', 1, 'enchantment', false, true, []],
  ['misty-step', 'Misty Step', 2, 'conjuration', false, false, []],
  ['ray-of-sickness', 'Ray of Sickness', 1, 'necromancy', false, false, []],
  ['web', 'Web', 2, 'conjuration', false, true, []],
  ['false-life', 'False Life', 1, 'necromancy', false, false, []],
  [
    'ray-of-enfeeblement',
    'Ray of Enfeeblement',
    2,
    'necromancy',
    false,
    true,
    [],
  ],
  ['barkskin', 'Barkskin', 2, 'transmutation', false, false, ['druid']],
  [
    'lesser-restoration',
    'Lesser Restoration',
    2,
    'abjuration',
    false,
    false,
    ['druid'],
  ],
  ['moonbeam', 'Moonbeam', 2, 'evocation', false, true, ['druid']],
  [
    'pass-without-trace',
    'Pass without Trace',
    2,
    'abjuration',
    false,
    true,
    ['druid'],
  ],
  ['spike-growth', 'Spike Growth', 2, 'transmutation', false, true, ['druid']],
  ['fireball', 'Fireball', 3, 'evocation', false, false, []],
  ['sleet-storm', 'Sleet Storm', 3, 'conjuration', false, true, ['druid']],
  ['lightning-bolt', 'Lightning Bolt', 3, 'evocation', false, false, []],
  ['stinking-cloud', 'Stinking Cloud', 3, 'conjuration', false, true, []],
  [
    'call-lightning',
    'Call Lightning',
    3,
    'conjuration',
    false,
    true,
    ['druid'],
  ],
  ['dispel-magic', 'Dispel Magic', 3, 'abjuration', false, false, ['druid']],
  ['plant-growth', 'Plant Growth', 3, 'transmutation', false, false, ['druid']],
  ['revivify', 'Revivify', 3, 'necromancy', false, false, ['druid']],
  ['blight', 'Blight', 4, 'necromancy', false, false, ['druid']],
  ['ice-storm', 'Ice Storm', 4, 'evocation', false, false, ['druid']],
  [
    'freedom-of-movement',
    'Freedom of Movement',
    4,
    'abjuration',
    false,
    false,
    ['druid'],
  ],
  ['polymorph', 'Polymorph', 4, 'transmutation', false, true, ['druid']],
  [
    'conjure-minor-elementals',
    'Conjure Minor Elementals',
    4,
    'conjuration',
    false,
    true,
    ['druid'],
  ],
  ['stone-shape', 'Stone Shape', 4, 'transmutation', false, false, ['druid']],
  ['antilife-shell', 'Antilife Shell', 5, 'abjuration', false, true, ['druid']],
  ['awaken', 'Awaken', 5, 'transmutation', false, false, ['druid']],
  [
    'commune-with-nature',
    'Commune with Nature',
    5,
    'divination',
    true,
    false,
    ['druid'],
  ],
  [
    'conjure-elemental',
    'Conjure Elemental',
    5,
    'conjuration',
    false,
    true,
    ['druid'],
  ],
  ['contagion', 'Contagion', 5, 'necromancy', false, false, ['druid']],
  [
    'greater-restoration',
    'Greater Restoration',
    5,
    'abjuration',
    false,
    false,
    ['druid'],
  ],
  ['insect-plague', 'Insect Plague', 5, 'conjuration', false, true, ['druid']],
  [
    'mass-cure-wounds',
    'Mass Cure Wounds',
    5,
    'abjuration',
    false,
    false,
    ['druid'],
  ],
  [
    'planar-binding',
    'Planar Binding',
    5,
    'abjuration',
    false,
    false,
    ['druid'],
  ],
  ['reincarnate', 'Reincarnate', 5, 'necromancy', false, false, ['druid']],
  ['scrying', 'Scrying', 5, 'divination', false, true, ['druid']],
  [
    'transmute-rock',
    'Transmute Rock',
    5,
    'transmutation',
    false,
    false,
    ['druid'],
  ],
  ['tree-stride', 'Tree Stride', 5, 'conjuration', false, true, ['druid']],
  ['wall-of-stone', 'Wall of Stone', 5, 'evocation', false, true, ['druid']],
  ['cone-of-cold', 'Cone of Cold', 5, 'evocation', false, false, []],
];
const cantripDice = (die: number) => ({
  type: 'character-level' as const,
  steps: [1, 5, 11, 17].map((minimumLevel, index) => ({
    minimumLevel,
    dice: { count: index + 1, die },
  })),
});
const richSpellContent: Readonly<Record<string, Partial<SpellDefinition>>> = {
  'thorn-whip': {
    range: '30 feet',
    components: { verbal: true, somatic: true, material: true, materialRequirement: 'the stem of a plant with thorns' },
    duration: 'Instantaneous',
    attackType: 'melee-spell',
    damage: [{ dice: { count: 1, die: 6 }, damageType: 'piercing' }],
    scaling: cantripDice(6),
    description: 'You create a vine-like whip covered in thorns that lashes at one creature in range. Make a melee spell attack. On a hit, the target takes piercing damage, and if it is Large or smaller, you can pull it up to 10 feet closer to you.',
    higherLevels: 'The damage increases by one die at character levels 5, 11, and 17.',
    content: { completeness: 'summary', source: 'phb-2024' },
  },
  'produce-flame': {
    range: 'Self', duration: '10 minutes',
    description: 'A flickering flame appears in your hand. It sheds light and harms neither you nor your equipment. While it lasts, you can take a Magic action to hurl fire at a creature or object within 60 feet, making a ranged spell attack.',
    attackType: 'ranged-spell',
    damage: [{ dice: { count: 1, die: 8 }, damageType: 'fire' }],
    scaling: cantripDice(8),
    higherLevels: 'The damage increases by one die at character levels 5, 11, and 17.',
    content: { completeness: 'summary', source: 'phb-2024' },
  },
  'call-lightning': {
    range: '120 feet', duration: 'Concentration, up to 10 minutes', savingThrow: 'dexterity',
    damage: [{ dice: { count: 3, die: 10 }, damageType: 'lightning' }],
    description: 'A storm cloud appears at a point in range. When it appears, and on later turns when you use a Magic action, choose a point beneath it. Lightning flashes down and creatures near that point make a Dexterity saving throw, taking lightning damage on a failed save or half as much on a success.',
    higherLevels: 'The damage increases by 1d10 for each spell-slot level above 3.',
    content: { completeness: 'summary', source: 'phb-2024' },
  },
  'cure-wounds': {
    range: 'Touch', duration: 'Instantaneous',
    healing: [{ dice: { count: 2, die: 8 }, abilityModifier: 'wisdom' }],
    description: 'A creature you touch regains Hit Points. This spell has no effect on Constructs or Undead.',
    higherLevels: 'The healing increases by 2d8 for each spell-slot level above 1.',
    content: { completeness: 'summary', source: 'phb-2024' },
  },
  'tree-stride': {
    range: 'Self', duration: 'Concentration, up to 1 minute',
    description: 'You gain the ability to enter a living tree and move from inside it to another living tree of the same kind within range. Each tree must be Large or bigger.',
    content: { completeness: 'summary', source: 'phb-2024' },
  },
};
const spells = Object.fromEntries(
  spellRows.map(
    ([id, name, level, school, ritual, concentration, classIds]) => [
      id,
      ({
        id,
        name,
        level,
        school,
        ritual,
        concentration,
        classIds,
        castingTime: 'Action',
        range: 'See imported rules content',
        duration: concentration
          ? 'Concentration'
          : 'See imported rules content',
        components: {
          verbal: true,
          somatic: true,
          material: false,
        },
        tags: [
          ...(name.toLowerCase().includes('heal') || name.includes('Cure')
            ? (['healing'] as const)
            : []),
          ...(concentration ? (['control'] as const) : (['utility'] as const)),
        ],
        description: 'Detailed rules text is not yet bundled for this spell. Its verified structured mechanics remain available.',
        content: { completeness: 'mechanics-only', source: 'phb-2024' },
        source: phb2024,
        ...richSpellContent[id],
      } satisfies SpellDefinition),
    ],
  ),
);
const grant = (
  id: string,
  spellId: string,
  sourceType: SpellGrant['sourceType'],
  sourceId: string,
  level: number,
  opts: Partial<SpellGrant> = {},
): SpellGrant => ({
  id,
  spellId,
  sourceType,
  sourceId,
  unlockedAtCharacterLevel: level,
  alwaysPrepared: true,
  countsAgainstPreparedLimit: false,
  castingAbility: 'wisdom',
  mayUseSpellSlots: true,
  source: phb2024,
  ...opts,
});
const landData = {
  arid: [
    [3, 'fire-bolt'],
    [3, 'burning-hands'],
    [3, 'blur'],
    [5, 'fireball'],
    [7, 'blight'],
    [9, 'wall-of-stone'],
  ],
  polar: [
    [3, 'ray-of-frost'],
    [3, 'fog-cloud'],
    [3, 'hold-person'],
    [5, 'sleet-storm'],
    [7, 'ice-storm'],
    [9, 'cone-of-cold'],
  ],
  temperate: [
    [3, 'shocking-grasp'],
    [3, 'sleep'],
    [3, 'misty-step'],
    [5, 'lightning-bolt'],
    [7, 'freedom-of-movement'],
    [9, 'tree-stride'],
  ],
  tropical: [
    [3, 'acid-splash'],
    [3, 'ray-of-sickness'],
    [3, 'web'],
    [5, 'stinking-cloud'],
    [7, 'polymorph'],
    [9, 'insect-plague'],
  ],
} as const;
const grants: SpellGrant[] = Object.entries(landData)
  .flatMap(([land, rows]) =>
    rows.map(([level, id]) =>
      grant(`land-${land}-${id}`, id, 'subclass', 'circle-of-the-land', level, {
        landType: land as SpellGrant['landType'],
      }),
    ),
  )
  .concat([
    grant('chthonic-chill-touch', 'chill-touch', 'species', 'chthonic', 1, {
      mayUseSpellSlots: false,
    }),
    grant('chthonic-false-life', 'false-life', 'species', 'chthonic', 3, {
      freeUseResourceId: 'chthonic-false-life-use',
    }),
    grant(
      'chthonic-ray-of-enfeeblement',
      'ray-of-enfeeblement',
      'species',
      'chthonic',
      5,
      { freeUseResourceId: 'chthonic-ray-of-enfeeblement-use' },
    ),
  ]);
export const defaultRuleRegistry: RuleRegistry = {
  druidPrimalOrders: {
    magician: {
      id: 'magician',
      name: 'Magician',
      grants: ['additional-druid-cantrip', 'wisdom-skill-bonus'],
      choices: ['additional-cantrip', 'skill-bonus-target'],
      source: phb2024,
    },
    warden: {
      id: 'warden',
      name: 'Warden',
      grants: ['medium-armor', 'martial-weapons'],
      choices: [],
      source: phb2024,
    },
  },
  classes: {
    druid: {
      id: 'druid',
      name: 'Druid',
      hitDie: 8,
      primaryAbility: 'wisdom',
      savingThrows: ['intelligence', 'wisdom'],
      availableSkills: [
        'animalHandling',
        'arcana',
        'insight',
        'medicine',
        'nature',
        'perception',
        'religion',
        'survival',
      ],
      skillChoices: 2,
      armorTraining: ['Light armor', 'Shields'],
      weaponTraining: ['Simple weapons'],
      toolTraining: ['Herbalism Kit'],
      spellcastingAbility: 'wisdom',
      subclassUnlockLevel: 3,
      featureIds: featureList
        .filter((f) => f.ownerId === 'druid')
        .map((f) => f.id),
      progression: progression.map(
        ([
          level,
          cantripsKnown,
          preparedSpells,
          spellSlots,
          wild,
          featureIds,
        ]) => ({
          level,
          cantripsKnown,
          preparedSpells,
          spellSlots,
          featureIds,
          resourceMaximums: wild
            ? { 'wild-shape': wild }
            : ({} as Readonly<Record<string, number>>),
        }),
      ),
      source: phb2024,
    },
  },
  subclasses: {
    'circle-of-the-land': {
      id: 'circle-of-the-land',
      name: 'Circle of the Land',
      parentClassId: 'druid',
      unlockLevel: 3,
      featureIds: [
        'land-circle-spells',
        'land-natures-aid',
        'land-natural-recovery',
      ],
      source: phb2024,
    },
  },
  species: {
    tiefling: {
      id: 'tiefling',
      name: 'Tiefling',
      creatureType: 'Humanoid',
      size: 'Medium',
      speed: 30,
      featureIds: ['tiefling-darkvision', 'tiefling-otherworldly-presence'],
      optionIds: ['chthonic'],
      source: phb2024,
    },
  },
  speciesOptions: {
    chthonic: {
      id: 'chthonic',
      name: 'Chthonic Legacy',
      parentSpeciesId: 'tiefling',
      featureIds: ['chthonic-legacy'],
      grantIds: [
        'chthonic-chill-touch',
        'chthonic-false-life',
        'chthonic-ray-of-enfeeblement',
      ],
      source: phb2024,
    },
  },
  backgrounds: {
    farmer: {
      id: 'farmer',
      name: 'Farmer',
      abilityOptions: ['strength', 'constitution', 'wisdom'],
      skills: ['animalHandling', 'nature'],
      tool: "Carpenter's Tools",
      originFeatId: 'tough',
      equipmentRefs: ['farmer-equipment-a', 'farmer-equipment-b'],
      featureIds: ['farmer-skills'],
      source: phb2024,
    },
  },
  feats: {
    tough: {
      id: 'tough',
      name: 'Tough',
      category: 'origin',
      featureIds: ['tough-durability'],
      source: phb2024,
    },
  },
  features: Object.fromEntries(featureList.map((f) => [f.id, f])),
  spells,
  spellGrants: Object.fromEntries(grants.map((g) => [g.id, g])),
  resources: {
    'wild-shape': {
      id: 'wild-shape',
      name: 'Wild Shape',
      ownerType: 'class',
      ownerId: 'druid',
      minimumLevel: 2,
      maximum: {
        type: 'by-class-level',
        classId: 'druid',
        values: { 2: 2, 3: 2, 4: 2, 5: 2, 6: 3, 7: 3, 8: 3, 9: 3 },
      },
      recovery: [
        { restType: 'short', amount: 1 },
        { restType: 'long', amount: 'all' },
      ],
      source: phb2024,
    },
    'chthonic-false-life-use': {
      id: 'chthonic-false-life-use',
      name: 'False Life free use',
      ownerType: 'species',
      ownerId: 'chthonic',
      minimumLevel: 3,
      maximum: { type: 'constant', value: 1 },
      recovery: [{ restType: 'long', amount: 'all' }],
      source: phb2024,
    },
    'chthonic-ray-of-enfeeblement-use': {
      id: 'chthonic-ray-of-enfeeblement-use',
      name: 'Ray of Enfeeblement free use',
      ownerType: 'species',
      ownerId: 'chthonic',
      minimumLevel: 5,
      maximum: { type: 'constant', value: 1 },
      recovery: [{ restType: 'long', amount: 'all' }],
      source: phb2024,
    },
  },
};
